package stdlibport.client.tv.fungus.shows;

import stdlibport.client.tv.fungus.Show;

public class Techquickie extends Show {

    @Override
    public String[] getEpisodes() {
        return new String[] {
                "https://youtube.com/embed/7QDWTMlSbzM = Why Is SMS Texting Still Popular",
                "https://youtube.com/embed/mmuAmXRk9lA = Why Can39t You Install Windows on an Xbox",
                "https://youtube.com/embed/3YfZcNUhBKY = What Makes ALL Your Electronics Work  Firmware Explained",
                "https://youtube.com/embed/nfY9-tbaZYc = How To Buy a TV for GAMING",
                "https://youtube.com/embed/Sgowh_da82g = Why do Gamers Still LOVE Old School CRT Tube TVs",
                "https://youtube.com/embed/D5kGXI8vUKg = Where Did SOUND CARDS Go",
                "https://youtube.com/embed/jQCY-jmoY5o = Why WiFi 6 Will CHANGE Gaming",
                "https://youtube.com/embed/VyIXf-l8Uv0 = Get the Most MONEY For Your Old Tech",
                "https://youtube.com/embed/1vaEBgceqdA = Can You Have TOO Many CPU Cores",
                "https://youtube.com/embed/7Ue0J-4qxDM = Are Hard Drives DISAPPEARING",
                "https://youtube.com/embed/zY8GG_5H6Ss = Why Do Screens Need Ugly BORDERS",
                "https://youtube.com/embed/H79vPVkwE14 = Why are upload speeds so SLOW",
                "https://youtube.com/embed/muZpR2gjwAQ = Is Your Webcam SPYING On You",
                "https://youtube.com/embed/VIEIbY17qDw = RANT Why Phone Roaming SUCKS",
                "https://youtube.com/embed/c6jITjq8UsA = Why Cable TV Is Such A RIPOFF",
                "https://youtube.com/embed/4JNBDwd40is = Don39t Trust ANYTHING You See  Deepfakes Explained",
                "https://youtube.com/embed/-K9jpNf_hx4 = How does phone power sharing work",
                "https://youtube.com/embed/B1V1mGUg1M8 = Give Your GPU a Break  Variable Rate Shading Explained",
                "https://youtube.com/embed/KYS3RlWybS0 = What the heck is Filmmaker Modequot",
                "https://youtube.com/embed/QCPGpUpegjk = Flip Phones Are BACK",
                "https://youtube.com/embed/Tay4Pz-PQDc = Why is Water Cooling Better",
                "https://youtube.com/embed/5_1BlGGSccM = Why IBM GAVE UP on Making PCs",
                "https://youtube.com/embed/MUn9Y8WlVQU = Can you Control a Computer with your MIND",
                "https://youtube.com/embed/xT9F39Pd3og = What Makes Apps and Websites So Reliable",
                "https://youtube.com/embed/TeCnUKoJjF8 = The FIGHT Over 6 GHz WiFi",
                "https://youtube.com/embed/G1Ke-H8I1uk = How Does LIGHT Carry Data",
                "https://youtube.com/embed/yyv9Y2miV64 = Is Overclocking Worth It",
                "https://youtube.com/embed/dTiSmkYbL8g = How ONE Company Keeps The Internet Running",
                "https://youtube.com/embed/omEm40cIsI0 = Is Your SSD FAST Enough",
                "https://youtube.com/embed/qgbp697tdgk = How Does FREE Software Make MONEY",
                "https://youtube.com/embed/2pWu_rJUiJs = The History of CPU Overclocking",
                "https://youtube.com/embed/keWRRQvps2o = Five Reasons to QUIT Facebook",
                "https://youtube.com/embed/UJqyxmhDWTM = Why Piracy Will NEVER DIE",
                "https://youtube.com/embed/_v2Lbs5PGdk = Amazon's MadeUp Holiday  Prime Day Explained",
                "https://youtube.com/embed/bW7NjQLpHx0 = Why Tube TVs DIED",
                "https://youtube.com/embed/Q0W7fHJMnyg = Theres ANOTHER Version of USB",
                "https://youtube.com/embed/JNDGGM1Pv7E = Why Do Websites Just STOP Working",
                "https://youtube.com/embed/ORS-V_lAwrI = Why Foldable Phones Are a BAD Idea",
                "https://youtube.com/embed/LnKGTZIAup0 = Is Your Monitor FAST Enough  Refresh Rates",
                "https://youtube.com/embed/JsTLbSpt_9c = How UnderScreen Cameras Will KILL the Notch",
                "https://youtube.com/embed/JlxhxV8w0u4 = Origins of the DARK WEB",
                "https://youtube.com/embed/wkKjES0-iR4 = Why Does Apple's Monitor Stand Cost $999 ??",
                "https://youtube.com/embed/_U7rBD2ps6A = Can a Monitor be TOO Bright",
                "https://youtube.com/embed/rmrYO7jTM9M = How Much Phone Storage Do You Need",
                "https://youtube.com/embed/c9lcY4xREWk = Is 8K Completely POINTLESS",
                "https://youtube.com/embed/lvhaVjpYm_M = Is 5G SAFE",
                "https://youtube.com/embed/NkknclAeUZ8 = How AMD is Making CPUs More Affordable  Chiplets Explained",
                "https://youtube.com/embed/-PIPMndlTqA = Are Macs REALLY Safer",
                "https://youtube.com/embed/iCEw6M0bUzw = Why Websites Load SLOWLY  Even With FAST Internet",
                "https://youtube.com/embed/EO4fhKnfJl0 = Do You Need a BIGGER Hard Drive",
                "https://youtube.com/embed/2LOkI3Xyd_E = Is Your Internet FAST Enough",
                "https://youtube.com/embed/8i67R5bnb14 = Why Intel is STRUGGLING Against AMD",
                "https://youtube.com/embed/pCbchoYg__k = Can You REALLY Trust Online Reviews",
                "https://youtube.com/embed/qnF8BOgzLuQ = How Apple Came Back From The DEAD",
                "https://youtube.com/embed/5gfzgx5orIM = Why Monitors DON'T Look Their BestYet OLED",
                "https://youtube.com/embed/xitRUMrOfMc = How Fortnite TOOK Over Gaming  Battle Royale Explained",
                "https://youtube.com/embed/3OiJ8h28-wI = Hide Your Secrets FOREVER  Erasing Data Securely",
                "https://youtube.com/embed/FWYckvfygV4 = Why Do Integrated Graphics SUCK",
                "https://youtube.com/embed/jl8uvhYFI6M = Is Google Stadia the FUTURE of Gaming",
                "https://youtube.com/embed/xiYDWspiBr0 = The Program we HATE But Use Anyway PowerPoint",
                "https://youtube.com/embed/8fgg_tC9Qgg = Why Power Adapters Are So HUGE",
                "https://youtube.com/embed/mlS8jywmCF4 = Robots Are Already Running YOUR Life",
                "https://youtube.com/embed/4RKxCNiOZ74 = Why SelfDriving Cars DON39T Just CRASH",
                "https://youtube.com/embed/wIntcNdChDU = How Computers Can THINK FOR THEMSELVES",
                "https://youtube.com/embed/gShRBsahzXg = RANT The DUMBEST Thing About USB",
                "https://youtube.com/embed/Rga2N50Ek8o = The Marketing Is A LIE",
                "https://youtube.com/embed/IQ8tcMW2Gow = How iPhone KILLED the BlackBerry",
                "https://youtube.com/embed/KyJ9ryJVK38 = Is Premium Audio a SCAM",
                "https://youtube.com/embed/215Wv23xgLA = Why You Don't See THESE On Phones Anymore",
                "https://youtube.com/embed/ZM2nhpb5138 = Can Bluetooth Actually Sound GOOD",
                "https://youtube.com/embed/zwlbDdsMEgA = The Most ANNOYING Windows Feature",
                "https://youtube.com/embed/SDjC5jklb3o = Is Windows Update Getting WORSE",
                "https://youtube.com/embed/xtByFblWaNM = The ONLY Way to Upgrade Your MacBook",
                "https://youtube.com/embed/RMojraRwxio = What Do HACKERS Do With YOUR Data",
        };
    }

}
