package stdlibport.client.tv.fungus.shows;

import stdlibport.client.tv.fungus.Show;

public class UnsolvedMysteries extends Show {

    @Override
    public String[] getEpisodes() {
        return new String[] {
                "https://youtube.com/embed/F3_mLWAbXuA = Unsolved Mysteries with Dennis Farina  S1 Ep 1",
                "https://youtube.com/embed/9L21L_MAp94 = Unsolved Mysteries with Dennis Farina  S1 Ep 2",
                "https://youtube.com/embed/Zdjf9hohEB8 = Unsolved Mysteries with Dennis Farina  S1 Ep 3",
                "https://youtube.com/embed/aQdDXUznUR0 = Unsolved Mysteries with Dennis Farina  S1 Ep 4",
                "https://youtube.com/embed/pFs_cQKbwNg = Unsolved Mysteries with Dennis Farina  S1 Ep 5",
                "https://youtube.com/embed/oM_CEU1d_lY = Unsolved Mysteries with Dennis Farina  S1 Ep 6",
                "https://youtube.com/embed/9pmLdX2WKW4 = Unsolved Mysteries with Dennis Farina  S1 Ep 7",
                "https://youtube.com/embed/kGCFyiIcj5c = Unsolved Mysteries with Dennis Farina  S1 Ep 8",
                "https://youtube.com/embed/vtiYGeWTAaE = Unsolved Mysteries with Dennis Farina  S1 Ep 9",
                "https://youtube.com/embed/8NPTYdmDyZ8 = Unsolved Mysteries with Dennis Farina  S1 Ep 10",
                "https://youtube.com/embed/CAMy7nyNq5g = Unsolved Mysteries with Dennis Farina  S1 Ep 11",
                "https://youtube.com/embed/6br1i0YUD6Y = Unsolved Mysteries with Dennis Farina  S1 Ep 12",
                "https://youtube.com/embed/adV-v6hs2ts = Unsolved Mysteries with Dennis Farina  S1 Ep 13",
                "https://youtube.com/embed/-lAUeiWJNoc = Unsolved Mysteries with Dennis Farina  S1 Ep 14",
                "https://youtube.com/embed/pTkAZW_zIwc = Unsolved Mysteries with Dennis Farina  S1 Ep 15",
                "https://youtube.com/embed/h6Q7ck77Sdk = Unsolved Mysteries with Dennis Farina  S1 Ep 16",
                "https://youtube.com/embed/9XdV_gQimmE = Unsolved Mysteries with Dennis Farina  S1 Ep 17",
                "https://youtube.com/embed/lRheHsxiJpU = Unsolved Mysteries with Dennis Farina  S1 Ep 18",
                "https://youtube.com/embed/MO8B5mo0rN8 = Unsolved Mysteries with Dennis Farina  S1 Ep 19",
                "https://youtube.com/embed/kRavemJ8D20 = Unsolved Mysteries with Dennis Farina  S1 Ep 20",
                "https://youtube.com/embed/SbtXmayUQnk = Unsolved Mysteries with Dennis Farina  S1 Ep 21",
                "https://youtube.com/embed/fdOhG28B2jU = Unsolved Mysteries with Dennis Farina  S1 Ep 22",
                "https://youtube.com/embed/ZptMWY12ltE = Unsolved Mysteries with Dennis Farina  S2 Ep 1",
                "https://youtube.com/embed/FWDiqPwc-qk = Unsolved Mysteries with Dennis Farina  S2 Ep 2",
                "https://youtube.com/embed/fsh-4mFXL7s = Unsolved Mysteries with Dennis Farina  S2 Ep 3",
                "https://youtube.com/embed/FEgfcu_a-sc = Unsolved Mysteries with Dennis Farina  S2 Ep 4",
                "https://youtube.com/embed/DPyjcnELgzQ = Unsolved Mysteries with Dennis Farina  S2 Ep 5",
                "https://youtube.com/embed/M_ni5laY5OY = Unsolved Mysteries with Dennis Farina  S2 Ep 6",
                "https://youtube.com/embed/RqPHxA6EFdE = Unsolved Mysteries with Dennis Farina  S2 Ep 7",
                "https://youtube.com/embed/xg8p8bc59mI = Unsolved Mysteries with Dennis Farina  S2 Ep 8",
                "https://youtube.com/embed/aJ29TaZy6GA = Unsolved Mysteries with Dennis Farina  S2 Ep 9",
                "https://youtube.com/embed/q0H95bL6qDw = Unsolved Mysteries with Dennis Farina  S2 Ep 10",
                "https://youtube.com/embed/5XgMLnonbBA = Unsolved Mysteries with Dennis Farina  S2 Ep 11",
                "https://youtube.com/embed/1FFZ07ipZZU = Unsolved Mysteries with Dennis Farina  S2 Ep 12",
                "https://youtube.com/embed/mRQPbpqN6Xg = Unsolved Mysteries with Dennis Farina  S2 Ep 13",
                "https://youtube.com/embed/QlKLwGPtDgg = Unsolved Mysteries with Dennis Farina  S2 Ep 14",
                "https://youtube.com/embed/fjDyFa6UH3Q = Unsolved Mysteries with Dennis Farina  S2 Ep 15",
                "https://youtube.com/embed/5IoelU7iTmI = Unsolved Mysteries with Dennis Farina  S2 Ep 16",
                "https://youtube.com/embed/bXGwfH-1_SM = Unsolved Mysteries with Dennis Farina  S2 Ep 17",
                "https://youtube.com/embed/9w-1QX9rz9s = Unsolved Mysteries with Dennis Farina  S2 Ep 18",
                "https://youtube.com/embed/0xOcA6Nv_tE = Unsolved Mysteries with Dennis Farina  S2 Ep 19",
                "https://youtube.com/embed/51VAqjbofq8 = Unsolved Mysteries with Dennis Farina  S2 Ep 20",
                "https://youtube.com/embed/DNfJM49r7Nw = Unsolved Mysteries with Dennis Farina  S2 Ep 21",
                "https://youtube.com/embed/8vmlqnpeoGI = Unsolved Mysteries with Dennis Farina  S2 Ep 22",
                "https://youtube.com/embed/FZNz-Mof4Tc = Unsolved Mysteries with Dennis Farina  S3 Ep 1",
                "https://youtube.com/embed/jwd7yzAAZLI = Unsolved Mysteries with Dennis Farina  S3 Ep 2",
                "https://youtube.com/embed/3C-qt9I8SEU = Unsolved Mysteries with Dennis Farina  S3 Ep 3",
                "https://youtube.com/embed/Qrs1WdBgbiE = Unsolved Mysteries with Dennis Farina  S3 Ep 4",
                "https://youtube.com/embed/j9j01e1tMvc = Unsolved Mysteries with Dennis Farina  S3 Ep 5",
                "https://youtube.com/embed/sRuW5a6wnuY = Unsolved Mysteries with Dennis Farina  S3 Ep 6",
                "https://youtube.com/embed/YMnENjg45n8 = Unsolved Mysteries with Dennis Farina  S3 Ep 7",
                "https://youtube.com/embed/-gm5Uu6ihWI = Unsolved Mysteries with Dennis Farina  S3 Ep 8",
                "https://youtube.com/embed/oJ0FoKxoRZs = Unsolved Mysteries with Dennis Farina  S3 Ep 9",
                "https://youtube.com/embed/JY2j5Dj3jHI = Unsolved Mysteries with Dennis Farina  S3 Ep 10",
                "https://youtube.com/embed/oYRvn2piNKw = Unsolved Mysteries with Dennis Farina  S3 Ep 11",
                "https://youtube.com/embed/W4eVafGn_mU = Unsolved Mysteries with Dennis Farina  S3 Ep 12",
                "https://youtube.com/embed/P_452NU9WYQ = Unsolved Mysteries with Dennis Farina  S3 Ep 13",
                "https://youtube.com/embed/nZ0QG5myqdc = Unsolved Mysteries with Dennis Farina  S3 Ep 14",
                "https://youtube.com/embed/0jJDk5yqDAQ = Unsolved Mysteries with Dennis Farina  S3 Ep 15",
                "https://youtube.com/embed/B97nMxMK1AA = Unsolved Mysteries with Dennis Farina  S3 Ep 16",
                "https://youtube.com/embed/NuRL-O8Xqs8 = Unsolved Mysteries with Dennis Farina  S3 Ep 17",
                "https://youtube.com/embed/IzGXduq3mmc = Unsolved Mysteries with Dennis Farina  S3 Ep 18",
                "https://youtube.com/embed/PHrkPCY0VAY = Unsolved Mysteries with Dennis Farina  S3 Ep 19",
                "https://youtube.com/embed/KylV1s9AsTU = Unsolved Mysteries with Dennis Farina  S3 Ep 20",
                "https://youtube.com/embed/ic-n2tQ-2Tg = Unsolved Mysteries with Dennis Farina  S3 Ep 21",
                "https://youtube.com/embed/dMkdBeazTN8 = Unsolved Mysteries with Dennis Farina  S3 Ep 22",
                "https://youtube.com/embed/zqdlASdlmS4 = Unsolved Mysteries with Dennis Farina  S4 Ep 1",
                "https://youtube.com/embed/Dx6pTdP2xZQ = Unsolved Mysteries with Dennis Farina  S4 Ep 2",
                "https://youtube.com/embed/FGMbQJqXi-Y = Unsolved Mysteries with Dennis Farina  S4 Ep 3",
                "https://youtube.com/embed/08NX2GH4bwk = Unsolved Mysteries with Dennis Farina  S4 Ep 4",
                "https://youtube.com/embed/nAdMjyjoOpg = Unsolved Mysteries with Dennis Farina  S4 Ep 5",
                "https://youtube.com/embed/CT0TwtcKlkw = Unsolved Mysteries with Dennis Farina  S4 Ep 6",
                "https://youtube.com/embed/py6RZKsHMng = Unsolved Mysteries with Dennis Farina  S4 Ep 7",
                "https://youtube.com/embed/Rg5Jzp_ycho = Unsolved Mysteries with Dennis Farina  S4 Ep 8",
                "https://youtube.com/embed/HfLhI6QblvU = Unsolved Mysteries with Dennis Farina  S4 Ep 9",
                "https://youtube.com/embed/w9RhCv42gjQ = Unsolved Mysteries with Dennis Farina  S4 Ep 10",
                "https://youtube.com/embed/IEMWMNt9-Bc = Unsolved Mysteries with Dennis Farina  S4 Ep 11",
                "https://youtube.com/embed/dY9z-TlUqmc = Unsolved Mysteries with Dennis Farina  S4 Ep 12",
                "https://youtube.com/embed/QF-atnkUjpk = Unsolved Mysteries with Dennis Farina  S4 Ep 13",
                "https://youtube.com/embed/x5kepaDQ_B8 = Unsolved Mysteries with Dennis Farina  S4 Ep 14",
                "https://youtube.com/embed/NrD9TEbcu2o = Unsolved Mysteries with Dennis Farina  S4 Ep 15",
                "https://youtube.com/embed/rK4a3VcgwT4 = Unsolved Mysteries with Dennis Farina  S4 Ep 16",
                "https://youtube.com/embed/uHXTDq14ZAE = Unsolved Mysteries with Dennis Farina  S4 Ep 17",
                "https://youtube.com/embed/E0v9A8ZudEU = Unsolved Mysteries with Dennis Farina  S4 Ep 18",
                "https://youtube.com/embed/iq6sVhCM28c = Unsolved Mysteries with Dennis Farina  S4 Ep 19",
                "https://youtube.com/embed/ctfHd94AIeA = Unsolved Mysteries with Dennis Farina  S4 Ep 20",
                "https://youtube.com/embed/y8RgHyAKCMY = Unsolved Mysteries with Dennis Farina  S4 Ep 21",
                "https://youtube.com/embed/Z-0Ezo9CBZU = Unsolved Mysteries with Dennis Farina  S4 Ep 22",
                "https://youtube.com/embed/kiP3wSR_h_w = Unsolved Mysteries with Dennis Farina  S5 Ep 1",
                "https://youtube.com/embed/7VfUXe3Uxic = Unsolved Mysteries with Dennis Farina  S5 Ep 2",
                "https://youtube.com/embed/VTjyUqVYKws = Unsolved Mysteries with Dennis Farina  S5 Ep 3",
                "https://youtube.com/embed/Lu9JXWdbH7g = Unsolved Mysteries with Dennis Farina  S5 Ep 4",
                "https://youtube.com/embed/fgWBeCEaiP8 = Unsolved Mysteries with Dennis Farina  S5 Ep 5",
                "https://youtube.com/embed/5sH3M_4CR_0 = Unsolved Mysteries with Dennis Farina  S5 Ep 6",
                "https://youtube.com/embed/Nu941v-98fM = Unsolved Mysteries with Dennis Farina  S5 Ep 7",
                "https://youtube.com/embed/FlnFtjd0MFs = Unsolved Mysteries with Dennis Farina  S5 Ep 8",
                "https://youtube.com/embed/1RtebUR1MQs = Unsolved Mysteries with Dennis Farina  S5 Ep 9",
                "https://youtube.com/embed/gdezz3p-UdM = Unsolved Mysteries with Dennis Farina  S5 Ep 10",
                "https://youtube.com/embed/WiWw_OepcVU = Unsolved Mysteries with Dennis Farina  S5 Ep 11",
                "https://youtube.com/embed/cejvJuF9oL0 = Unsolved Mysteries with Dennis Farina  S5 Ep 12",
        };
    }

}
