package tv.fungus.shows;

import tv.fungus.Show;

public class CheddarExplains extends Show {

    @Override
    public String[] getEpisodes() {
        return new String[] {
                "https://youtube.com/embed/sLbQ5sPrybU = How Popcorn Went From Banned to Saving Movies",
                "https://youtube.com/embed/5gXOQ39xWz8 = How The Microphone Changed The Way We Sing",
                "https://youtube.com/embed/He-xViFnvRA = Why Are Identical Movies Released at the Same Time",
                "https://youtube.com/embed/kEPpOGyvCmc = The World Is Running Out Of Sand",
                "https://youtube.com/embed/hDX7xYKDOlo = The quotLiesquot Advertisers Can Legally Tell You",
                "https://youtube.com/embed/sMXzeiwZN-M = Why It Makes Sense That Airlines Overbook",
                "https://youtube.com/embed/lU830Kx9hMM = Why Doesn't the US Just Use the Metric System",
                "https://youtube.com/embed/Sl09t_Bz9jU = The One Place Your Signature Still Matters",
                "https://youtube.com/embed/lisZBL3_aW8 = What Is the Ideal Size for a City Block",
                "https://youtube.com/embed/DE6aUSNvak0 = We All Secretly Love Spoilers",
                "https://youtube.com/embed/3MlyAvUfh8E = Why The East Sides of Cities Are Poorer Than The West",
                "https://youtube.com/embed/OdDsV19DBCU = Why New Yorkers Insisted On a quotWorsequot Subway Map",
                "https://youtube.com/embed/LN6_S5_FE3o = How Footpaths Help Shape Our Technology",
                "https://youtube.com/embed/fMaric5Afdg = How Halloween Popups Beat the Recession",
                "https://youtube.com/embed/gnJPtYx4H8E = Why The Polls Keep Getting It Wrong",
                "https://youtube.com/embed/6OEL-p68Aq4 = Open Layout Homes Have A Surprising Problem",
                "https://youtube.com/embed/QVsNP5KLl9s = The Misguided War on Solitaire",
                "https://youtube.com/embed/kvskkXlvhS4 = The Real Reason for the New York Skyline Gap",
                "https://youtube.com/embed/hiuINZG-CcI = The Intentionally Poor Design Of Phone Pads",
                "https://youtube.com/embed/TkLfwIsiWGU = Why Are Ripped Jeans More Expensive",
                "https://youtube.com/embed/s2GKdYB76ZY = The Internet is In Danger of Drowning",
                "https://youtube.com/embed/-dP-lPvfSoQ = Can Empathy Prevent A Robot Uprising",
                "https://youtube.com/embed/fnxyR7IT3rs = Is the AntiStraw Movement as Forward As It Seems",
                "https://youtube.com/embed/A8S-uCeE0-Q = How Hackers Hold Towns Hostage",
                "https://youtube.com/embed/35byJxDIX88 = The Person Who Cut You Off In Traffic Is Right",
                "https://youtube.com/embed/1EVr1I6oll0 = How Uruguay Became an Unlikely World Cup Powerhouse",
                "https://youtube.com/embed/3vFRcgu1xr8 = Why Drug Dealers are Choosing the United States Postal Service",
                "https://youtube.com/embed/sagQxnIjb78 = What a World Cup Without the US Means for Fox",
                "https://youtube.com/embed/pjs1_E3hRv0 = How Missile Technology Changed The Game of Basketball",
                "https://youtube.com/embed/zwjhhdRbJnc = Who Defends Earth From Asteroids",
                "https://youtube.com/embed/74TcB5mTJWs = How Your Browsing Behavior Affects What You Pay Online",
                "https://youtube.com/embed/va4AoZtzH68 = What Part of Space Should NASA Explore Next",
                "https://youtube.com/embed/fyWyr4RGhVo = Robotic Exotic Dancers Prove No Job Is Safe",
                "https://youtube.com/embed/uopSzlYo7sg = How Virtual Horse Armor Paved the Way for PayToWin in Gaming",
                "https://youtube.com/embed/grkhoRHCMGg = How Lemons Led to the Rise of the Sicilian Mafia",
                "https://youtube.com/embed/bV5sMLSrA9E = The Hidden Economy Behind NYC Street Vending",
                "https://youtube.com/embed/NiVv6T0gepY = NASA Solar Sails Could Allow Interstellar Travel",
                "https://youtube.com/embed/3WqVALJqhcs = How Cord Cutting Is Signaling quotInnovate or Diequot To Traditional Media",
                "https://youtube.com/embed/pwiSJu_7VnE = How Close Are We To Living Like the Jetsons",
                "https://youtube.com/embed/tDUXsvFoew4 = Why You Should Care About The quotInternet of Thingsquot",
                "https://youtube.com/embed/8Kuvpjw1fAo = Could Going Helmetless Solve Football39s Brain Injury Problem",
                "https://youtube.com/embed/Z3auNH64624 = Why Are Fast Food Logos Red And Why Are They Changing to Green",
                "https://youtube.com/embed/m56_9Q2oCAk = What is a Ponzi Scheme",
                "https://youtube.com/embed/WapWFxDr0o0 = Apple Slowed Down Your iPhone But Is It Planned Obsolescence",
                "https://youtube.com/embed/I85ZmEdGLNM = The Dot Com Bubble",
                "https://youtube.com/embed/OoWSYp2e1Fs = Do College Football Players Need Free Lifelong Heath Care",
                "https://youtube.com/embed/A2JAmnHUbIo = The War For Your Internet Browsing Activity",
                "https://youtube.com/embed/fVG3KL3lyEA = How NASA Innovations Make Money for America",
                "https://youtube.com/embed/Z2ThyioUQrc = The Capitalistic amp Religious Reasons Why Breakfast is the quotMost Important Meal of the Dayquot",
                "https://youtube.com/embed/AVSjsYHX6eM = Why Ski Resorts Are Dying",
                "https://youtube.com/embed/bVcibhlOKyE = Why All Films Have This Disclaimer",
                "https://youtube.com/embed/IGooWUHcpjI = The Real Story Behind the Star Wars Crawl",
                "https://youtube.com/embed/HQi6gJwsRNs = The Anatomy of the Presidential Motorcade",
                "https://youtube.com/embed/uKwOyA-pOTY = Why American Yards Are Shrinking",
                "https://youtube.com/embed/0FfU6M-25iw = The Surprising Reason We Don39t Hitchhike Anymore",
                "https://youtube.com/embed/XN-tSpQZmYk = How Expanding Bike Lanes Can Actually Decrease Traffic",
                "https://youtube.com/embed/df8QAgTJIio = The Inaudible Sounds That Make Movies Scarier",
                "https://youtube.com/embed/0e4vO11XQPw = How an Unlikely Logo Helped Save a Broken City",
                "https://youtube.com/embed/GIm8arSogvY = The Font That Makes Everyone Read Faster",
                "https://youtube.com/embed/2DcR6nAwcgA = Malls Of The Future Are ReInventing Retail",
                "https://youtube.com/embed/SX1xmaKPb9o = The Secret Infrastructure Beneath NYC",
                "https://youtube.com/embed/VrSSUGCaVMc = Why Does New York City Smell So Bad",
                "https://youtube.com/embed/mOz4ZoEMMl8 = Why Skyscraper Cemeteries Are On The Rise",
                "https://youtube.com/embed/11fX-0BtMaI = Why Are So Many Cartoon Mothers Deceased",
                "https://youtube.com/embed/L-GFqOWLVmU = Airports Are Designed To Make You Spend Money",
                "https://youtube.com/embed/hWWrOtaEVtw = Pirates Didn39t Really Talk Like That",
                "https://youtube.com/embed/-yWfqnU9Oso = Why Don't Buses Have Seatbelts",
                "https://youtube.com/embed/U5wcuVGYESM = Why Every TV Show Has A Noticeably Boring Ep",
                "https://youtube.com/embed/4jUzPh2lJ-M = The Spelling Bee Isn39t Just About Memorization",
                "https://youtube.com/embed/4Z922g9R6xE = How James Holzhauer Broke Jeopardy",
                "https://youtube.com/embed/rZOpDve8ARA = The Fake Sounds Companies Add To Products",
                "https://youtube.com/embed/EqHIn6eWfus = The Hidden Logic Behind Area Codes",
                "https://youtube.com/embed/6sImpkYwSLM = Could This Subway Car Save NYC Transit",
                "https://youtube.com/embed/bCaFRN3aaP8 = Is Dark Mode Actually Better For Your Eyes",
                "https://youtube.com/embed/DgjBizysCJw = Why You Turn Down The Radio When You39re Lost",
                "https://youtube.com/embed/FXkRjM3a4-A = Media Companies Are Turning Streaming Back Into Cable",
                "https://youtube.com/embed/Wvn64vr-sc8 = How quotBadquot Coffee Took Over America",
                "https://youtube.com/embed/1xjwPQy_OMQ = Using the Wrong Emojis Could Send You To Jail",
                "https://youtube.com/embed/vbsoO2c7gCM = The Unseen Inefficiency of Escalator Etiquette",
                "https://youtube.com/embed/WMM2KCTRX2k = The Real Way Blockbusters Make Their Money",
                "https://youtube.com/embed/yyWYvovLvMQ = A Flaw In Street Design May Be Costing Lives",
                "https://youtube.com/embed/TfzEPtLPnP4 = Why 3D Logos Fell Out of Favor Overnight",
                "https://youtube.com/embed/1ThnxSaExzU = Why All Movie Posters Look the Same",
                "https://youtube.com/embed/Zy_ahwS14Gg = Wooden Skyscrapers Are On The Rise",
                "https://youtube.com/embed/vodSSgHgYxM = How Focus Music Hacks Your Brain",
                "https://youtube.com/embed/KMwGpkQYgNE = Should We Pay to Pee",
        };
    }

}
