package tv.fungustv.shows;

import tv.fungustv.Show;

public class PinkPanther extends Show {

    @Override
    public String[] getEpisodes() {
        return new String[] {
                "https://youtu.be/eImu_Ds3aao = The Pink Panther Show Episode 25  Pinknic",
                "https://youtu.be/FVCezIrbqzM = The Pink Panther Show Episode 26  Pink Panic",
                "https://youtu.be/_RGVT8hH_rA = The Pink Panther Show Episode 27  Pink Posies",
                "https://youtu.be/l2eCQa8NsOw = The Pink Panther Show Episode 28  Pink of the Litter",
                "https://youtu.be/tntOzR4suTU = The Pink Panther Show Episode 29  In the Pink",
                "https://youtu.be/3uPEWMdz3MU = The Pink Panther Show Episode 30  Jet Pink",
                "https://youtu.be/uFJFRyZDYMw = The Pink Panther Show Episode 31  Pink Paradise",
                "https://youtu.be/r_s-7_JnMQg = The Pink Panther Show Episode 32  Pinto Pink",
                "https://youtu.be/j4FiEzGygp8 = The Pink Panther Show Episode 33  Congratulations It39s Pink",
                "https://youtu.be/WZQYyS9Lljw = The Pink Panther Show Episode 34  Prefabricated Pink",
                "https://youtu.be/LLKG5PtBbBg = The Pink Panther Show Episode 35  The Hand is Pinker Than the Eye",
                "https://youtu.be/dRi9eQm4Wck = The Pink Panther Show Episode 36  Pink Outs",
                "https://youtu.be/QhYP-etpGvg = The Pink Panther Show Episode 37  Sky Blue Pink",
                "https://youtu.be/OYUcnAHDpZM = The Pink Panther Show Episode 38  Pinkadilly Circus",
                "https://youtu.be/FmQclg80Vj4 = The Pink Panther Show Episode 39  Psychedelic Pink",
                "https://youtu.be/3xDJ3xyVMms = The Pink Panther Show Episode 40  Come on In The Water39s Pink",
                "https://youtu.be/wpQX5i9MO4c = The Pink Panther Show Episode 41  PutPut Pink",
                "https://youtu.be/hI2srW4Yku8 = The Pink Panther Show Episode 42  GI Pink",
                "https://youtu.be/ZFoWYhn5er4 = The Pink Panther Show Episode 43  Lucky Pink",
                "https://youtu.be/b70IDc7e5Qs = The Pink Panther Show Episode 44  The Pink Quarterback",
                "https://youtu.be/FETaXhxCOeA = The Pink Panther Show Episode 45  Twinkle Twinkle Little Pink",
                "https://youtu.be/iESUR_b02jk = The Pink Panther Show Episode 46  Pink Valiant",
                "https://youtu.be/z93qRyEY_wQ = The Pink Panther Show Episode 47  The Pink Pill",
                "https://youtu.be/iA9KJ-j28YI = The Pink Panther Show Episode 48  Prehistoric Pink",
                "https://youtu.be/F5g5BrtdDfc = The Pink Panther Show Episode 49  Pink in the Clink",
                "https://youtu.be/xy-h1Dl7Lrs = The Pink Panther Show Episode 50  Little Beaux Pink",
                "https://youtu.be/19Fw68jTv10 = The Pink Panther Show Episode 51  Tickled Pink",
                "https://youtu.be/u-T6UEVh6jw = The Pink Panther Show Episode 52  Pink Sphinx",
                "https://youtu.be/ApneYCea0c8 = The Pink Panther Show Episode 53  Pink Is a Many Splintered Thing",
                "https://youtu.be/LuyJBnSn1Wc = The Pink Panther Show Episode 54  The Pink Package Plot",
                "https://youtu.be/Q0uiA1oInYI = The Pink Panther Show Episode 55  Pinkcome Tax",
                "https://youtu.be/16CGbt0a8HI = The Pink Panther Show Episode 56  PinkARella",
                "https://youtu.be/ALuQmS3diKQ = The Pink Panther Show Episode 57  Pink Pest Control",
                "https://youtu.be/QMQhJ9FriNs = The Pink Panther Show Episode 58  Think Before You Pink",
                "https://youtu.be/rdjnkb4ONWk = The Pink Panther Show Episode 59  Slink Pink",
                "https://youtu.be/Tibe5o4kqWQ = The Pink Panther Show Episode 60  In the Pink of the Night",
                "https://youtu.be/6ktqmkYEfYU = The Pink Panther Show Episode 61  Pink on the Cob",
                "https://youtu.be/Vuhp5vv5hoU = The Pink Panther Show Episode 62  Extinct Pink",
                "https://youtu.be/9ebKDfj51uY = The Pink Panther Show Episode 63  A Fly in the Pink",
                "https://youtu.be/EyF2mbti5O0 = The Pink Panther Show Episode 64  Pink Blue Plate",
                "https://youtu.be/490c6oNbHhQ = The Pink Panther Show Episode 65  Pink TubaDore",
                "https://youtu.be/FvG0aQNT37Q = The Pink Panther Show Episode 66  Pink Pranks",
                "https://youtu.be/yAWcBMXy91Y = The Pink Panther Show Episode 67  The Pink Flea",
                "https://youtu.be/k95KG9zHZyQ = The Pink Panther Show Episode 68  Psst Pink",
                "https://youtu.be/W_K6RYC1N8k = The Pink Panther Show Episode 69  Gong with the Pink",
                "https://youtu.be/1GxMu6Oky2I = The Pink Panther Show Episode 70  PinkIn",
                "https://youtu.be/MmQspTVQtY0 = The Pink Panther Show Episode 71  Pink 8 Ball",
                "https://youtu.be/Sp3gF8Sf5Vk = The Pink Panther Show Episode 72  Pink Aye",
                "https://youtu.be/M2LjgoewC2I = The Pink Panther Show Episode 73  Trail of the Lonesome Pink",
                "https://youtu.be/ADGR-Z4kd1A = The Pink Panther Show Episode 74  Pink DaVinci",
                "https://youtu.be/VYH8RwRphhA = The Pink Panther Show Episode 75  Pink Streaker",
                "https://youtu.be/yrbGKhI_uYQ = The Pink Panther Show Episode 76  Salmon Pink",
                "https://youtu.be/TYj8Xd9JKQg = The Pink Panther Show Episode 77  Forty Pink Winks",
                "https://youtu.be/qHD_fmkO8ew = The Pink Panther Show Episode 78  Pink Plasma",
                "https://youtu.be/xVjZk3Mrw3o = The Pink Panther Show Episode 79  Pink Elephant",
                "https://youtu.be/DilDuEbG9Zc = The Pink Panther Show Episode 80  Keep Our Forests Pink",
                "https://youtu.be/xNg9oimPUPw = The Pink Panther Show Episode 81  Bobolink Pink",
                "https://youtu.be/uIuld-1xBts = The Pink Panther Show Episode 82  It39s Pink But Is It Mink",
                "https://youtu.be/48i6jfcUhUo = The Pink Panther Show Episode 83  Pink Campaign",
                "https://youtu.be/4b23cXEv5zs = The Pink Panther Show Episode 84  The Scarlet Pinkernel",
                "https://youtu.be/6PvGiXaAJpo = The Pink Panther Show Episode 85  Mystic Pink",
                "https://youtu.be/vLaqt0c2b7g = The Pink Panther Show Episode 86  The Pink of Arabee",
                "https://youtu.be/R8s1QU9csFg = The Pink Panther Show Episode 87  The Pink Pro",
                "https://youtu.be/IyNpW4ruXY8 = The Pink Panther Show Episode 88  Pink Piper",
                "https://youtu.be/Ttn-JwUCfEU = The Pink Panther Show Episode 89  Pinky Doodle",
                "https://youtu.be/E09tfDKmdi8 = The Pink Panther Show Episode 90  Sherlock Pink",
                "https://youtu.be/W0vuD1hfWAY = The Pink Panther Show Episode 91  Rocky Pink",
                "https://youtu.be/CRw9MPchTMA = The Pink Panther Show Episode 92  Therapeutic Pink",
                "https://youtu.be/Xr1ae0fzaSM = The Pink Panther Show Episode 93  Pink Pictures",
                "https://youtu.be/EXcg6W9TV_U = The Pink Panther Show Episode 94  Pink Arcade",
                "https://youtu.be/tltWdrhjHqk = The Pink Panther Show Episode 95  Pink Lemonade",
                "https://youtu.be/v4UkD7U88NQ = The Pink Panther Show Episode 96  Pink Trumpet",
                "https://youtu.be/A02tw43oi_I = The Pink Panther Show Episode 97  Sprinkle Me Pink",
                "https://youtu.be/x00NFHmcPKs = The Pink Panther Show Episode 98  Dietic Pink",
                "https://youtu.be/Quvu4V0SJKY = The Pink Panther Show Episode 99  Pink UFO",
                "https://youtu.be/rZ_8ZH08fxo = The Pink Panther Show Episode 100  Pink Lightning",
                "https://youtu.be/P195UZs0HmE = The Pink Panther Show Episode 101  Cat and the Pinkstalk",
                "https://youtu.be/vvBstOh9jqk = The Pink Panther Show Episode 102  Pink Daddy",
                "https://youtu.be/SadjA8XcD8k = The Pink Panther Show Episode 103  Pink SWAT",
                "https://youtu.be/thTwnFNSnWM = The Pink Panther Show Episode 104  Pink and Shovel",
                "https://youtu.be/A8dfa14WgMQ = The Pink Panther Show Episode 105  Pinkologist",
                "https://youtu.be/bddsMdqosRI = The Pink Panther Show Episode 106  Yankee Doodle Pink",
                "https://youtu.be/ItsDCB82hV8 = The Pink Panther Show Episode 107  Pink Press",
                "https://youtu.be/zRonaFOHi88 = The Pink Panther Show Episode 108  Pet Pink Pebbles",
                "https://youtu.be/PNVGPFbUAp8 = The Pink Panther Show Episode 109  The Pink of Bagdad",
                "https://youtu.be/yHz4LSZTfE0 = The Pink Panther Show Episode 110  Pink in the Drink",
                "https://youtu.be/D5Jv4Zff9_E = The Pink Panther Show Episode 111  Pink Bananas",
                "https://youtu.be/nLjyYRztVSw = The Pink Panther Show Episode 112  PinkTails for Two",
                "https://youtu.be/bi6gSPU0lZg = The Pink Panther Show Episode 113  Pink ZZZ",
                "https://youtu.be/6RrMtZqEaSQ = The Pink Panther Show Episode 114  Star Pink",
                "https://youtu.be/CMqBm0nOPDk = The Pink Panther Show Episode 115  Pink Breakfast",
                "https://youtu.be/yDs-teEeb2w = The Pink Panther Show Episode 116  Toro Pink",
                "https://youtu.be/VDpcrG4rPBQ = The Pink Panther Show Episode 117  Pink Quackers",
                "https://youtu.be/_q1heR46hQI = The Pink Panther Show Episode 118  String Along in Pink",
                "https://youtu.be/tO1pqDFDVPk = The Pink Panther Show Episode 119  Pink in the Woods",
                "https://youtu.be/ryTdJtRZlx8 = The Pink Panther Show Episode 120  Pink Pull",
                "https://youtu.be/N02b9KTa054 = The Pink Panther Show Episode 121  Spark Plug Pink",
                "https://youtu.be/nACvj5vFiXQ = The Pink Panther Show Episode 122  Doctor Pink",
                "https://youtu.be/B7_ipr8mKGY = The Pink Panther Show Episode 123  Pink Suds",
                "https://youtu.be/jDv0szBsASY = The Pink Panther Show Episode 124  Supermarket Pink",
        };
    }

}
