package tv.fungustv.shows;

import tv.fungustv.Show;

public class TwoCents extends Show {

    @Override
    public String[] getEpisodes() {
        return new String[] {
                "https://youtube.com/embed/7i6mPvBv488 = 5 Biggest Financial Scams And How To Avoid Them",
                "https://youtube.com/embed/u3qNhJrFl2E = 5 Money Questions to Ask Your Partner",
                "https://youtube.com/embed/y72iyLPOv8E = 5 Questions To Ask Before Investing",
                "https://youtube.com/embed/nyd5sCFkJds = 5 Strange Investment Crazes",
                "https://youtube.com/embed/U1IvJClaqNI = 5 Tips For A Better Side Hustle",
                "https://youtube.com/embed/n1b7piSmmME = 5 Ways People Are Dumb With Money",
                "https://youtube.com/embed/VmawC2raK28 = 9 Hacks for Moving on a Budget",
                "https://youtube.com/embed/GIMsbgIQiDE = Are credit unions better than big banks",
                "https://youtube.com/embed/jbsBNPddn4o = Are Millennials Bad with Money",
                "https://youtube.com/embed/soVaufg4-QY = Are quotFreequot Video Games Really Free",
                "https://youtube.com/embed/CZxPMnLnWJQ = Are Women Better With Money",
                "https://youtube.com/embed/sVKQn2I4HDM = Budgeting Basics",
                "https://youtube.com/embed/7iww5zIuzyA = Can You Really Get Rich Quick",
                "https://youtube.com/embed/qFxCgQiHuDg = Can You Really Protect Your Identity Online",
                "https://youtube.com/embed/8si7cqw9wm0 = Can You Really Retire in Your 30s",
                "https://youtube.com/embed/770HVHEI284 = Do Kids Need to Learn About Money",
                "https://youtube.com/embed/ykNnj2JJMTY = Do You Really Want to Be Your Own Boss",
                "https://youtube.com/embed/eQi9mcQoRq4 = Does Wealth Make You Meaner",
                "https://youtube.com/embed/tpI0XWjIsqI = How Bankruptcy Works",
                "https://youtube.com/embed/TtJXl6pk0Z4 = How Cars Keep You POOR",
                "https://youtube.com/embed/6cRg9bnSnvg = How Do Tax Brackets Actually Work",
                "https://youtube.com/embed/zOHJUVSAeDw = How Do You Actually Buy a House",
                "https://youtube.com/embed/VqFa3NQHqug = How Do You Legally Set Up a Business",
                "https://youtube.com/embed/Gy0P-ePwJNI = How Do Your Tax Dollars Get Spent",
                "https://youtube.com/embed/pAAv7gWV6SU = How Eating Out Keeps You Poor",
                "https://youtube.com/embed/eUCuH0sb-pc = How Much Should I Charge Probably More Than You Think",
                "https://youtube.com/embed/0wEayQ_5rjQ = How Retailers Stalk You Online",
                "https://youtube.com/embed/249Gc7FDWRI = How Risky Is The Stock Market",
                "https://youtube.com/embed/HHdowfpwbrc = How To Ask For A Raise",
                "https://youtube.com/embed/b-hDg7699S0 = How to Do Market Research",
                "https://youtube.com/embed/1VAZmcJ6_50 = How To Save Money At The Supermarket",
                "https://youtube.com/embed/fD4wqwa48Z4 = How to save money on your wedding",
                "https://youtube.com/embed/WTtjmdyTCRM = Im Young amp Healthy Can I Skip Health Insurance",
                "https://youtube.com/embed/CxHarNKW7Go = Is Cash Going Extinct",
                "https://youtube.com/embed/bbDKMtLxdSA = Is It BAD to Play the Lottery",
                "https://youtube.com/embed/Y2DYsktUyeA = Is It Smart To Outsource Your Chores",
                "https://youtube.com/embed/KA66Wcp1QEc = Is Retirement Even POSSIBLE",
                "https://youtube.com/embed/S1Om2rSQcDE = Money Is Imaginary Should You Trust It",
                "https://youtube.com/embed/OxhznRLPj_k = Should I Invest In Cannabis Stocks",
                "https://youtube.com/embed/ChSpkZ0jVxc = Should You Buy a House",
                "https://youtube.com/embed/ggvlgNMr_NE = Should You Buy Bitcoin",
                "https://youtube.com/embed/uudPHdBBPO4 = Somethings Eating Your Money",
                "https://youtube.com/embed/evDE1EIYygo = The History Of Christmas Shopping",
                "https://youtube.com/embed/6se8TltCOoc = The Truth About Airline Miles",
                "https://youtube.com/embed/i3YCPPKRW2Q = Welcome to TWO CENTS",
                "https://youtube.com/embed/0Ut9XtNlT4g = What Are The Most Lucrative Trades",
                "https://youtube.com/embed/MA0vDPrRhJc = What College Majors Are Worth the Money",
                "https://youtube.com/embed/GcnCuzSzEWM = What Do Financial Experts Do",
                "https://youtube.com/embed/ozbGWLtZdoY = What Goes Into Your Credit Score",
                "https://youtube.com/embed/jxZa90pSYzc = What the Heck Is a Mutual Fund",
                "https://youtube.com/embed/u5eewhr7KKY = What The Heck Is An Index Fund",
                "https://youtube.com/embed/vMJ2dkSc8Ok = What The Heck Is an IRA",
                "https://youtube.com/embed/_PXFVNWINQc = What the Heck Is the DOW",
                "https://youtube.com/embed/sHSaUqoKjkA = Whats a Good Return on Investment",
                "https://youtube.com/embed/PvEUj_mRfIo = Whats The Fastest Way To Pay Off Debt",
                "https://youtube.com/embed/X7_tKPVq0Mo = Whats The Real Cost of Dying",
                "https://youtube.com/embed/72mPrnnsQ3s = Whats the real cost of having a baby",
                "https://youtube.com/embed/ma3Mt5BPlTE = Whats the Real Cost of Owning A Pet",
                "https://youtube.com/embed/yD7CAjt65kc = When Should I Tip",
                "https://youtube.com/embed/TdoNAJlo9kU = Why Americans Are Failing the Grade at Financial Literacy",
                "https://youtube.com/embed/aLwRZibUqL0 = Why Its More Expensive To Be Poor",
                "https://youtube.com/embed/vftjBTjFlzI = Why You NEED an Emergency Fund",
                "https://youtube.com/embed/gttUS9tKOes = Will Social Security Be Around for Millennials",
                "https://youtube.com/embed/ZAKH739y46g = You Should Talk To Your Parents About Money",
        };
    }

}
